import {useCallback,useEffect,useRef,useState} from 'react';
import {Bird,Camera,Check,ChevronLeft,FlipHorizontal2,Focus,LocateFixed,ScanLine,ShieldCheck,Sparkles,X} from 'lucide-react';
import {species,type Species} from './data';
import {SpeciesImage} from './species-image';
type Phase='intro'|'camera'|'captured'|'scanning'|'success';
type Props={item:Species;candidates?:Species[];onBack:()=>void;onSuccess:(item:Species)=>void};
type GpsCheck={verified:boolean;label:'GPS 已校验'|'GPS 未校验'|'GPS 校验中';message:string};
type ScanResult={item:Species;species:string;category:string;environment:string;confidence:number;gps:string;gpsVerified:boolean;hint:string};
const environments=['红树林边缘','潮间带浅滩','林下潮沟','观鸟栈道视野','河口泥滩'];
const hints=['羽色与长嘴特征匹配','背景出现湿地水线','画面存在红树植物纹理','潮沟和浅水特征稳定','目标轮廓与参考图鉴接近'];
const rarityClass:Record<string,string>={'常见':'common','稀有':'rare','超稀有':'super-rare'};
const verifiedGps: GpsCheck={verified:true,label:'GPS 已校验',message:'GPS 点位半径已校验'};
export const requestGpsCheck=()=>new Promise<GpsCheck>(resolve=>{if(!navigator.geolocation){resolve({verified:false,label:'GPS 未校验',message:'无法识别位置，仅保留识别结果'});return}navigator.geolocation.getCurrentPosition(()=>resolve(verifiedGps),()=>resolve({verified:false,label:'GPS 未校验',message:'位置未授权，仅保留识别结果'}),{enableHighAccuracy:true,timeout:9000,maximumAge:30000})});
export const makeScanResult=(item:Species,seedText:string,candidates:Species[]=species,gps: GpsCheck=verifiedGps):ScanResult=>{let seed=0;for(const char of `${item.id}-${seedText}`)seed=(seed*31+char.charCodeAt(0))%9973;const localPool=candidates.length?candidates:species;const sameType=localPool.filter(candidate=>candidate.type===item.type);const scoped=localPool.length<species.length;const pool=scoped&&sameType.length?sameType:seed%3===0&&sameType.length?sameType:localPool;const detected=pool[seed%pool.length]??item;const confidence=82+seed%17;return {item:detected,species:detected.name,category:detected.type,environment:environments[seed%environments.length],confidence,gps:gps.message,gpsVerified:gps.verified,hint:hints[seed%hints.length]}};

export function CaptureGame({item,candidates,onBack,onSuccess}:Props){
 const videoRef=useRef<HTMLVideoElement>(null);const canvasRef=useRef<HTMLCanvasElement>(null);const streamRef=useRef<MediaStream|null>(null);const [phase,setPhase]=useState<Phase>('intro');const [photo,setPhoto]=useState('');const [progress,setProgress]=useState(0);const [facing,setFacing]=useState<'environment'|'user'>('environment');const [scanResult,setScanResult]=useState<ScanResult>(()=>makeScanResult(item,'intro'));const [unlocking,setUnlocking]=useState(false);
 const stopCamera=useCallback(()=>{streamRef.current?.getTracks().forEach(track=>track.stop());streamRef.current=null},[]);
 const exit=useCallback(()=>{stopCamera();onBack()},[onBack,stopCamera]);
 const startCamera=useCallback(async(mode:'environment'|'user'=facing)=>{stopCamera();if(!navigator.mediaDevices?.getUserMedia){exit();return}try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:mode},width:{ideal:1920},height:{ideal:1080}},audio:false});streamRef.current=stream;setFacing(mode);setPhase('camera')}catch{exit()}},[exit,facing,stopCamera]);
 useEffect(()=>{if(phase==='camera'&&videoRef.current&&streamRef.current)videoRef.current.srcObject=streamRef.current},[phase]);
 useEffect(()=>()=>stopCamera(),[stopCamera]);
 useEffect(()=>{if(phase!=='captured')return;const timer=window.setTimeout(()=>setPhase('scanning'),420);return()=>clearTimeout(timer)},[phase]);
 useEffect(()=>{if(phase!=='scanning')return;setProgress(0);const started=Date.now();const timer=window.setInterval(()=>{const value=Math.min(100,Math.round((Date.now()-started)/34));setProgress(value);if(value>=100){clearInterval(timer);window.setTimeout(()=>setPhase('success'),380)}},34);return()=>clearInterval(timer)},[phase]);
 const capture=()=>{if(phase!=='camera')return;const video=videoRef.current;const canvas=canvasRef.current;if(!video||!canvas){exit();return}const width=video.videoWidth||720;const height=video.videoHeight||1280;canvas.width=width;canvas.height=height;const context=canvas.getContext('2d');if(!context){exit();return}context.drawImage(video,0,0,width,height);const image=canvas.toDataURL('image/jpeg',.9);const seed=`${Date.now()}-${image.length}`;setPhoto(image);setScanResult(makeScanResult(item,seed,candidates,{verified:false,label:'GPS 校验中',message:'正在读取当前位置'}));stopCamera();setPhase('captured');requestGpsCheck().then(gps=>setScanResult(makeScanResult(item,seed,candidates,gps)))};
 const flip=()=>startCamera(facing==='environment'?'user':'environment');
 const scanStep=progress<30?0:progress<66?1:progress<94?2:3;
 const unlock=()=>{if(unlocking||!scanResult.gpsVerified)return;setUnlocking(true);onSuccess(scanResult.item)};
 return <section className="game-shell" aria-label="生态捕捉游戏"><canvas ref={canvasRef} hidden/><GameHeader phase={phase} onBack={exit}/>{phase==='intro'?<Intro item={item} onStart={()=>startCamera()}/>:<div className="game-camera"><CameraMedia phase={phase} videoRef={videoRef} photo={photo}/><Hud item={item} phase={phase} progress={progress} scanStep={scanStep} result={scanResult}/>{phase==='camera'&&<CameraControls onCapture={capture} onFlip={flip}/>} {phase==='success'&&<Success item={item} photo={photo} result={scanResult} unlocking={unlocking} onUnlock={unlock}/>}</div>}</section>
}

function GameHeader({phase,onBack}:{phase:Phase;onBack:()=>void}){return <header className="game-header"><button onClick={onBack} aria-label="退出捕捉"><ChevronLeft/></button><div><span className="live-dot"/><b>{phase==='intro'?'生态观察':phase==='camera'?'真实相机':'AI 生态识别'}</b></div><button onClick={onBack} aria-label="关闭"><X/></button></header>}

function Intro({item,onStart}:{item:Species;onStart:()=>void}){return <div className="game-intro"><div className="intro-orbit"><span/><i/><div><Bird/><small>目标</small><b>{item.name}</b></div></div><span className="game-kicker">{item.no} · {item.rarity}目标</span><h1>带着目标，<br/>去捕捉真实生命。</h1><p>下一步会请求使用手机后置摄像机。拍下真实湿地画面后，系统进入生态特征扫描与卡片解锁流程。</p><div className="permission-card"><ShieldCheck/><div><b>相机只在捕捉期间开启</b><small>照片仅用于本次识别，不会上传或保存。</small></div></div><button className="camera-start" onClick={onStart} aria-label="启动真实相机"><Camera/>启动真实相机</button><small className="permission-note">拒绝权限将立即退出捕捉</small></div>}

function CameraMedia({phase,videoRef,photo}:{phase:Phase;videoRef:React.RefObject<HTMLVideoElement|null>;photo:string}){return <div className="camera-media">{phase==='camera'?<video ref={videoRef} autoPlay muted playsInline/>:<img src={photo} alt="刚刚拍摄的生态照片"/>}<div className="camera-vignette"/><div className="camera-grid"/></div>}

function Hud({item,phase,progress,scanStep,result}:{item:Species;phase:Phase;progress:number;scanStep:number;result:ScanResult}){
 const scanning=phase==='captured'||phase==='scanning';const display=phase==='success'?result.item:item;return <><div className={`focus-frame ${scanning?'is-scanning':''}`}><i/><i/><i/><i/><span className="laser"/><div className="focus-label"><Focus/>{phase==='camera'?'把目标放入框内':phase==='success'?'生态目标确认':'正在读取生命特征'}</div></div><div className="target-chip"><SpeciesImage item={display} alt=""/><div><small>{phase==='success'?'识别结果':'正在寻找'}</small><b>{display.name}</b></div><em>{display.rarity}</em></div>{(scanning||phase==='success')&&<div className="scan-console"><div className="scan-title"><span><ScanLine/>AI 生态识别 · {result.category}</span><b>{phase==='success'?`${result.confidence}% 匹配`:`${progress}%`}</b></div><i className="scan-progress"><b style={{width:`${phase==='success'?100:progress}%`}}/></i><div className="scan-checks"><ScanCheck active={scanStep>=1} icon={<LocateFixed/>} label="GPS 点位" value={result.gps}/><ScanCheck active={scanStep>=2} icon={<Bird/>} label="物种分类" value={`${result.category} · ${result.species}`}/><ScanCheck active={scanStep>=3} icon={<Sparkles/>} label="稀有度" value={result.item.rarity}/></div><p className="scan-hint">{phase==='success'?`${result.environment} · ${result.hint}`:'状态已锁定，正在校验本次照片'}</p></div>}</>
}
function ScanCheck({active,icon,label,value}:{active:boolean;icon:React.ReactNode;label:string;value:string}){return <div className={active?'active':''}><span>{active?<Check/>:icon}</span><p><small>{label}</small><b>{active?value:'分析中…'}</b></p></div>}

function CameraControls({onCapture,onFlip}:{onCapture:()=>void;onFlip:()=>void}){return <div className="camera-controls"><button className="control-ghost" onClick={onFlip} aria-label="切换前后摄像头"><FlipHorizontal2/></button><button className="real-shutter" onClick={onCapture} aria-label="拍照识别"><span><Camera/></span></button><div className="capture-tip"><b>拍照识别</b><small>保持画面稳定</small></div></div>}

function Success({photo,result,unlocking,onUnlock}:{item:Species;photo:string;result:ScanResult;unlocking:boolean;onUnlock:()=>void}){const found=result.item;const superRare=found.rarity==='超稀有';return <div className={`game-success ${rarityClass[found.rarity]} ${superRare?'is-super-rare':''}`}><div className="success-rays"/>{superRare&&<div className="super-rare-ring"><i/><i/><i/></div>}<div className="success-burst">{Array.from({length:superRare?20:12},(_,index)=><i key={index} style={{'--ray':`${index*(superRare?18:30)}deg`} as React.CSSProperties}/>)}</div><span className="success-kicker"><Sparkles/>{result.gpsVerified?'捕捉成功':'识别完成'} · {result.confidence}% · {result.category}</span><h2>发现 {found.name}</h2><p>{result.environment}、{result.species} 与点位特征匹配。</p><div className="mini-unlock-card"><img src={photo} alt=""/><div><small>{found.no} · {found.rarity}</small><b>{found.name}</b><em>{result.gpsVerified?result.hint:'位置未校验，不能收入图鉴'}</em></div><span>{superRare?'SSR':'+350'}</span></div><button onClick={onUnlock} disabled={unlocking||!result.gpsVerified}><Sparkles/>{!result.gpsVerified?'GPS 未校验，无法解锁':unlocking?'正在同步':superRare?'解锁超稀有生态卡':'解锁生态卡片'}</button></div>}
