import {useState,type CSSProperties} from 'react';
import {ChevronRight,FlipHorizontal2,Leaf,Share2,Sparkles,Waves,X} from 'lucide-react';
import {type Species} from './data';
import {rarityClass} from './views';
import {SpeciesImage} from './species-image';

export function CardReveal({item,level=0,flipped,onFlip,onClose,onCollect,collected,canCollect=true}:{item:Species;level?:number;flipped:boolean;onFlip:()=>void;onClose:()=>void;onCollect:()=>void;collected:boolean;canCollect?:boolean}){
 const [sharing,setSharing]=useState(false);const displayLevel=Math.max(collected?1:0,level);
 const title=canCollect?collected?'再次观察完成':'发现新物种！':'生态卡片详情';
 return <div className="modal-backdrop"><div className="reveal-modal"><button className="modal-close" onClick={onClose}><X/></button><div className="unlock-title"><span><Sparkles size={14}/>{collected?'观察记录':'湿地新发现'}</span><h2>{title}</h2></div><button className={`flip-card ${flipped?'is-flipped':''}`} onClick={onFlip} aria-label="翻转生态卡片"><div className="flip-inner"><div className={`card-face card-front ${rarityClass[item.rarity]}`} style={{'--card-accent':item.color} as CSSProperties}><SpeciesImage item={item} alt={item.name}/><span className="card-texture"/><div className="card-frame"><header><b>{item.no}</b><span>{item.rarity}</span></header><footer><small>{item.type} · 深圳湿地图鉴 · Lv.{displayLevel}</small><h3>{item.name}</h3><i>{item.latin}</i><p>{item.tagline}</p></footer></div></div><CardBack item={item}/></div></button><button className="flip-hint" onClick={onFlip}><FlipHorizontal2 size={16}/>{flipped?'翻回卡面':'翻转卡片，看看它的故事'}</button>{collected&&<button data-testid="share-card-action" className="secondary wide" onClick={()=>setSharing(value=>!value)}><Share2 size={17}/>生成分享卡</button>}{sharing&&<div data-testid="share-card" className={`share-card ${rarityClass[item.rarity]}`}><span>Mudflat Go! 深圳湿地发现</span><h3>{item.name}</h3><p>{item.no} · {item.rarity} · Lv.{displayLevel}</p><small>{item.location}</small><b>{item.tagline}</b></div>}{canCollect?<button data-testid="collect-card-action" className="primary wide" onClick={onCollect}>{collected?'提升卡片等级':'同步到我的图鉴'}<ChevronRight size={18}/></button>:<p className="card-detail-tip">图鉴页只展示资料。想收入图鉴，需要到真实点位完成拍摄识别。</p>}</div></div>
}
function CardBack({item}:{item:Species}){return <div className="card-face card-back"><header><span><Leaf size={16}/>一分钟认识它</span><b>{item.no}</b></header><h3>{item.name}</h3><div className="fact-block"><span>它住在哪里？</span><p>{item.habitat}</p></div><div className="fact-block"><span>它从哪里来？</span><p>{item.route}</p></div><div className="fact-highlight"><Waves size={21}/><p><b>红树林为什么重要？</b>{item.importance}</p></div><small>Mudflat Go! · SHENZHEN</small></div>}
