import {useState,type CSSProperties} from 'react';
import {ArrowLeft,BadgeCheck,Bird,Camera,ChevronRight,Compass,LocateFixed,MapPin,ScanLine,Sparkles} from 'lucide-react';
import {getSpecies,wetlands,type Species,type Wetland} from './data';
import {SpeciesImage} from './species-image';
export {CaptureGame as CaptureView} from './capture-game';
export const rarityClass:Record<string,string>={'常见':'common','稀有':'rare','超稀有':'super-rare'};

export function MapView({onOpen,onCollection:_,unlockedLocationCount=2}:{onOpen:(item:Wetland)=>void;onCollection:()=>void;unlockedLocationCount?:number}){
 return <section className="map-page page-enter"><div className="hero-copy"><span className="hero-kicker"><Compass size={15}/>深圳湿地生态 × AI 图鉴收集游戏</span><h1>带着图鉴，<br/>去发现深圳<br/><em>湿地生命。</em></h1><p>先看见可能遇到的鸟、树和滩涂生物，再到真实点位拍摄识别。路线会按探索顺序一点点亮起。</p><div className="hero-actions"><button className="primary" onClick={()=>onOpen(wetlands[0])}>从第 1 站出发 <ChevronRight size={18}/></button></div><div className="season-strip"><span className="pulse-dot"/><b>今日建议</b><span>先完成福田红树林，再解锁下一站。</span></div></div><MapCanvas onOpen={onOpen} unlockedLocationCount={unlockedLocationCount}/></section>
}

function MapCanvas({onOpen,unlockedLocationCount}:{onOpen:(item:Wetland)=>void;unlockedLocationCount:number}){
 const [active,setActive]=useState(wetlands[0]);const mapUrl=`https://uri.amap.com/marker?position=${active.lng},${active.lat}&name=${encodeURIComponent(active.name)}&coordinate=gaode&callnative=0`;const viewport=mapViewport(active);const routePoints=wetlands.map(item=>toMapPosition(item,viewport));const unlockedRoutePoints=routePoints.slice(0,Math.max(1,Math.min(unlockedLocationCount,wetlands.length)));const activeIndex=wetlands.findIndex(item=>item.id===active.id);const activeLocked=activeIndex>=unlockedLocationCount;const points=(items:{left:number;top:number}[])=>items.map(item=>`${item.left},${item.top}`).join(' ');
 return <div className="map-card real-map-card"><div className="map-toolbar"><div><small>真实深圳湿地路线</small><b>{active.name}</b></div><a href={mapUrl} target="_blank" rel="noreferrer"><LocateFixed size={18}/>打开导航</a></div><div className="real-map"><div className="tile-map" aria-hidden="true">{viewport.tiles.map(tile=><img key={`${tile.x}-${tile.y}`} className="map-tile" src={`https://tile.openstreetmap.org/${tile.z}/${tile.x}/${tile.y}.png`} style={{left:`${tile.left}%`,top:`${tile.top}%`,width:`${tile.width}%`,height:`${tile.height}%`}} alt=""/>)}</div><svg data-testid="wetland-route" className="wetland-route" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><polyline className="route-base" points={points(routePoints)}/>{unlockedRoutePoints.length>1&&<polyline className="route-active" points={points(unlockedRoutePoints)}/>}</svg><div className="geo-markers">{wetlands.map((item,index)=>{const position=routePoints[index];const locked=index>=unlockedLocationCount;return <button key={item.id} className={`geo-marker ${active.id===item.id?'active':''} ${locked?'locked':'unlocked'}`} style={{'--accent':item.accent,left:`${position.left}%`,top:`${position.top}%`} as CSSProperties} onClick={()=>setActive(item)} aria-disabled={locked} aria-label={`定位到${item.name}`}><span><i>{index+1}</i></span><b>{item.name}</b><small data-testid="landmark-bubble" className="landmark-bubble"><em>第 {index+1} 站</em>{item.short}</small></button>})}</div><div className={`real-map-overlay ${activeLocked?'locked':''}`}><span>{activeLocked?'顺序未解锁':'当前地图焦点'}</span><b>{active.name}</b><small>{active.lat.toFixed(5)}, {active.lng.toFixed(5)} · {active.limited}</small><button data-testid="map-enter-location" disabled={activeLocked} onClick={()=>!activeLocked&&onOpen(active)}>{activeLocked?'先完成上一站解锁':`进入${active.name}`}</button></div><div className="map-pins">{wetlands.map((item,index)=>{const locked=index>=unlockedLocationCount;return <button key={item.id} data-testid="map-location" aria-disabled={locked} className={`${active.id===item.id?'active':''} ${locked?'locked':''}`} style={{'--accent':item.accent} as CSSProperties} onMouseEnter={()=>setActive(item)} onFocus={()=>setActive(item)} onClick={()=>setActive(item)} aria-label={`定位到${item.name}`}><span>{index+1}</span><b>{item.name}</b></button>})}</div></div><div className="mobile-location-list">{wetlands.map((item,index)=>{const locked=index>=unlockedLocationCount;return <button key={item.id} className={locked?'locked':''} aria-disabled={locked} onClick={()=>locked?setActive(item):onOpen(item)} onMouseEnter={()=>setActive(item)}><span style={{background:locked?'#87958d':item.accent}}><MapPin size={17}/></span><div><b>{item.name}</b><small>{locked?'按路线顺序解锁':`进入第 ${index+1} 站 · ${item.distance}`}</small></div><ChevronRight size={18}/></button>})}</div></div>
}

const TILE_SIZE=256,MAP_ZOOM=10,MAP_WIDTH=1280,MAP_HEIGHT=880;
function project(lat:number,lng:number,zoom=MAP_ZOOM){const scale=TILE_SIZE*2**zoom;const sin=Math.sin(lat*Math.PI/180);return {x:(lng+180)/360*scale,y:(.5-Math.log((1+sin)/(1-sin))/(4*Math.PI))*scale}}
function mapViewport(active:Wetland){const center=project(active.lat,active.lng);const startX=Math.floor((center.x-MAP_WIDTH/2)/TILE_SIZE)-1;const endX=Math.ceil((center.x+MAP_WIDTH/2)/TILE_SIZE)+1;const startY=Math.floor((center.y-MAP_HEIGHT/2)/TILE_SIZE)-1;const endY=Math.ceil((center.y+MAP_HEIGHT/2)/TILE_SIZE)+1;const max=2**MAP_ZOOM;const tiles=[];for(let x=startX;x<=endX;x++)for(let y=startY;y<=endY;y++)if(y>=0&&y<max){const wrapped=(x%max+max)%max;tiles.push({x:wrapped,y,z:MAP_ZOOM,left:50+(x*TILE_SIZE-center.x)/MAP_WIDTH*100,top:50+(y*TILE_SIZE-center.y)/MAP_HEIGHT*100,width:TILE_SIZE/MAP_WIDTH*100,height:TILE_SIZE/MAP_HEIGHT*100})}return {center,tiles}}
function toMapPosition(item:Wetland,viewport:ReturnType<typeof mapViewport>){const point=project(item.lat,item.lng);return {left:Math.min(96,Math.max(4,50+(point.x-viewport.center.x)/MAP_WIDTH*100)),top:Math.min(90,Math.max(14,50+(point.y-viewport.center.y)/MAP_HEIGHT*100))}}

export function LocationView({location,onBack,onChoose}:{location:Wetland;onBack:()=>void;onChoose:(item:Species)=>void}){
 const localSpecies=location.species.map(getSpecies);
 return <section className="detail-page page-enter"><button className="back-button" onClick={onBack}><ArrowLeft size={18}/>返回深圳地图</button><div className="location-hero"><div className="location-photo" style={{backgroundImage:`linear-gradient(90deg,rgba(8,27,24,.95),rgba(8,27,24,.25)),url(${localSpecies[0].image})`}}/><div className="location-content"><span className="eyebrow"><MapPin size={14}/>{location.distance} · GPS 可探索</span><h1>{location.name}</h1><p>{location.short}。先看看今天可能出现的生命，再选一个目标出发。</p><div className="location-metrics"><span><b>{localSpecies.length}</b><small>今日目标</small></span><span><b>86%</b><small>观测指数</small></span><span><b>+350</b><small>捕捉奖励</small></span></div></div></div><div className="section-heading"><div><span className="eyebrow"><Camera size={14}/>生态摄影参考</span><h2>这里可能遇见它们</h2><p>不是盲拍。先锁定一个真实目标，再带着图鉴去寻找。</p></div><span className="weather-chip">24°C · 东南风 2级</span></div><div className="species-grid">{localSpecies.map((item,index)=><SpeciesPreview key={item.id} item={item} featured={index===0} onClick={()=>onChoose(item)}/>)}</div><p className="photo-note">参考图来自深圳湿地观鸟与生态摄影资料整理。</p></section>
}

function SpeciesPreview({item,featured,onClick}:{item:Species;featured:boolean;onClick:()=>void}){
 return <button className={`species-preview ${featured?'featured':''}`} onClick={onClick} aria-label={`锁定${item.name}`}><SpeciesImage item={item} alt={item.name}/><span className="image-shade"/><div className="species-top"><span className={`rarity ${rarityClass[item.rarity]}`}>{item.rarity}</span>{featured&&<span className="limited-badge"><Sparkles size={12}/>点位限定</span>}</div><div className="species-copy"><small>{item.no} · {item.type}</small><h3>{item.name}</h3><p>{item.tagline}</p><div><span>{item.season}</span><span>锁定目标 <ChevronRight size={14}/></span></div></div></button>
}

export function TargetView({item,location,onBack,onStart}:{item:Species;location:Wetland;onBack:()=>void;onStart:()=>void}){
 return <section className="target-page page-enter"><button className="back-button" onClick={onBack}><ArrowLeft size={18}/>更换观察目标</button><div className="target-layout"><div className="target-photo"><SpeciesImage item={item} alt={item.name}/><div className="focus-corners"><i/><i/><i/><i/></div><span className="camera-meta">参考摄影 · 目标特征已载入</span></div><div className="target-panel"><span className={`rarity ${rarityClass[item.rarity]}`}>{item.rarity}目标</span><p className="target-number">目标 {item.no}</p><h1>{item.name}</h1><i>{item.latin}</i><p className="target-tagline">“{item.tagline}”</p><div className="target-checklist"><Check icon={<MapPin size={18}/>} title="探索点位" text={`${location.name} · GPS 半径 500m`}/><Check icon={<Bird size={18}/>} title="识别特征" text={targetFeatureText(item)}/><Check icon={<Sparkles size={18}/>} title="成功奖励" text="生态卡片 +350 · 图鉴等级成长"/></div><button className="primary wide" onClick={onStart}><ScanLine size={19}/>开始生态捕捉</button><small className="demo-hint">下一步将请求使用手机后置摄像机；拒绝权限会立即退出捕捉。</small></div></div></section>
}
function targetFeatureText(item:Species){if(item.type==='鸟类')return '羽色、嘴形、站姿与湿地背景联合匹配';if(item.type==='树木')return '叶形、根系、树皮与红树林环境联合匹配';return '体形、运动痕迹、泥滩环境与潮汐线索联合匹配'}
function Check({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div><span>{icon}</span><p><b>{title}</b><small>{text}</small></p><BadgeCheck size={19}/></div>}
